(() => {
  const translations = {
    fr: {
      'Domus Cultura — Creative Culture Office': 'Domus Cultura — Maison culturelle créative',
      'Shop — Domus Cultura': 'Boutique — Domus Cultura',
      'Artist Submissions — Domus Cultura': 'Candidatures artistiques — Domus Cultura',
      'Sounds': 'Sons', 'Art Shop': 'Boutique d’art', 'Art Journal': 'Journal d’art', 'Events': 'Événements', 'Art': 'Art',
      'Independent platform for art, architecture, image and sound · Switzerland': 'Plateforme indépendante pour l’art, l’architecture, l’image et le son · Suisse',
      'A cultural house in motion.': 'Une maison culturelle en mouvement.', 'Photography by Ben Taleb': 'Photographie par Ben Taleb', 'Sound by Juice+': 'Son par Juice+',
      '01 / Current': '01 / Actuel', 'Cover story · Photography': 'À la une · Photographie',
      'A visual journal of architecture, public space and the people who move through it.': 'Un journal visuel de l’architecture, de l’espace public et des personnes qui le traversent.',
      'Enter the project ↗': 'Entrer dans le projet ↗', 'Domus Index': 'Index Domus', 'Now': 'Maintenant',
      'Ben Taleb editions': 'Éditions Ben Taleb', 'Collect / Photography': 'Collectionner / Photographie', 'Juice+ weekly selections': 'Sélections hebdomadaires Juice+', 'Listen / Sound': 'Écouter / Son',
      'Atelier and gallery visits': 'Visites d’ateliers et de galeries', 'Attend / Events': 'Participer / Événements', 'Domus objects and editions': 'Objets et éditions Domus', 'Discover / Shop': 'Découvrir / Boutique',
      '02 / Field notes': '02 / Notes de terrain', 'People, art': 'Personnes, art', 'and the': 'et la', 'street.': 'rue.', 'Follow @domuscultura ↗': 'Suivre @domuscultura ↗',
      'Human presence / Reflection': 'Présence humaine / Reflet', 'Exhibition detail / Art': 'Détail d’exposition / Art', 'Space / Form': 'Espace / Forme', 'Street art / Found work': 'Art urbain / Œuvre trouvée', 'People / Collective space': 'Personnes / Espace collectif',
      '03 / Position': '03 / Position', 'Culture is a space': 'La culture est un espace', 'we build': 'que nous construisons', 'together.': 'ensemble.',
      'Domus Cultura brings contemporary art into everyday life through editions, encounters, field notes and sound. It is a platform for looking closely, listening deeply and making new work possible.': 'Domus Cultura inscrit l’art contemporain dans la vie quotidienne à travers des éditions, des rencontres, des notes de terrain et le son. Une plateforme pour regarder attentivement, écouter profondément et rendre possibles de nouvelles œuvres.',
      '04 / Art': '04 / Art', 'Good Morning World': 'Good Morning World', 'Architecture, public space and the quiet theatre of the city.': 'Architecture, espace public et théâtre silencieux de la ville.',
      'Fine-art photograph': 'Photographie d’art', 'View the first editions ↗': 'Voir les premières éditions ↗', '05 / Image': '05 / Image', 'Observe first.': 'Observer d’abord.', 'Then frame.': 'Puis cadrer.',
      'The photographic practice moves between constructed space and human presence—between distance, rhythm and direct encounter.': 'La pratique photographique circule entre espace construit et présence humaine — entre distance, rythme et rencontre directe.',
      'Original art inquiries ↗': 'Demandes d’œuvres originales ↗', '06 / Events': '06 / Événements', 'Gatherings with': 'Des rencontres avec', 'a point of view.': 'un point de vue.',
      'Coming soon': 'Bientôt', 'Art, conversation and a live selection by Juice+.': 'Art, conversation et sélection live par Juice+.', 'Register interest ↗': 'Manifester son intérêt ↗',
      'In development': 'En développement', 'Artist & Atelier Visits': 'Visites d’artistes et d’ateliers', 'Small-format encounters with artists and their working spaces.': 'Rencontres en petit comité avec des artistes et leurs espaces de travail.', 'Join the list ↗': 'Rejoindre la liste ↗',
      'Weekly selections by Juice+': 'Sélections hebdomadaires par Juice+', 'Listen ↗': 'Écouter ↗', 'Visits, conversations and field notes': 'Visites, conversations et notes de terrain', 'Read ↗': 'Lire ↗', 'Limited editions and cultural objects': 'Éditions limitées et objets culturels', 'Collect ↗': 'Collectionner ↗',
      'Open call / Artists': 'Appel ouvert / Artistes', 'Should we know': 'Devrait-on connaître', 'your work?': 'votre travail ?', 'Domus Cultura accepts rolling submissions for editorial features, studio visits, events and future collaborations.': 'Domus Cultura accepte les candidatures en continu pour des portraits éditoriaux, visites d’atelier, événements et futures collaborations.', 'Submit your practice ↗': 'Soumettre votre pratique ↗',
      '07 / Contact': '07 / Contact', 'Ideas, commissions': 'Idées, commandes', 'and collaborations.': 'et collaborations.', 'Switzerland · Worldwide': 'Suisse · Monde entier',
      'Independent art, editions & sound from Switzerland — Made to order, never held in inventory': 'Art indépendant, éditions et son depuis la Suisse — Produit à la commande, jamais en stock',
      'The Domus Cultura store': 'La boutique Domus Cultura', 'Art lives': 'L’art vit', 'among us.': 'parmi nous.', 'Limited photography by Ben Taleb, cultural objects, artist collaborations and weekly sound selections by Juice+.': 'Photographies limitées de Ben Taleb, objets culturels, collaborations artistiques et sélections sonores hebdomadaires de Juice+.',
      '01 — Shop the first drop': '01 — Première sortie', 'Collect the': 'Collectionner', 'world we see.': 'le monde que nous voyons.', 'Three focused collections, produced responsibly and released in considered quantities.': 'Trois collections ciblées, produites de manière responsable et publiées en quantités réfléchies.',
      'Fine-art photography': 'Photographie d’art', 'Ben Taleb Editions': 'Éditions Ben Taleb', 'From CHF 150': 'Dès CHF 150', 'Unframed black-and-white photographs on museum-grade Hahnemühle paper · three sizes · edition of 100.': 'Photographies noir et blanc non encadrées sur papier Hahnemühle de qualité musée · trois formats · édition de 100.', 'See three views ↗': 'Voir trois vues ↗',
      'Objects & apparel': 'Objets et vêtements', 'Domus Essentials': 'Essentiels Domus', 'From CHF 25': 'Dès CHF 25', 'T-shirts, sweatshirts, caps, mugs, totes and postcard sets—made only after purchase, with no inventory.': 'T-shirts, sweats, casquettes, mugs, sacs et cartes postales — produits uniquement après achat, sans stock.',
      'Guest artists': 'Artistes invités', 'Domus Collaborations': 'Collaborations Domus', 'Limited': 'Limité', 'Small-run editions made with invited artists across image, sound and material.': 'Petites séries réalisées avec des artistes invités autour de l’image, du son et de la matière.', 'Propose a collaboration ↗': 'Proposer une collaboration ↗',
      'Product viewer — Object study': 'Visualiseur produit — Étude d’objet', 'Click a view to inspect the front, reverse and material detail before ordering.': 'Cliquez sur une vue pour examiner le devant, le dos et la matière avant de commander.',
      'Front / heavyweight organic cotton': 'Devant / coton biologique épais', 'Reverse / numbered first drop': 'Dos / première sortie numérotée', 'Detail / collar and print texture': 'Détail / col et texture d’impression', 'Full image / Looking Up, Ben Taleb': 'Image complète / Looking Up, Ben Taleb', 'Paper detail / natural-white cotton rag': 'Détail du papier / coton blanc naturel', 'Scale view / medium edition': 'Vue à l’échelle / édition moyenne',
      'Wear the': 'Porter la', 'house.': 'maison.', 'Produced only when ordered. The launch garment will be sampled for fabric weight, print durability and fit before checkout opens.': 'Produit uniquement sur commande. Le vêtement sera testé pour son grammage, la durabilité de l’impression et la coupe avant l’ouverture des ventes.',
      '01 Front': '01 Devant', '02 Reverse': '02 Dos', '03 Detail': '03 Détail', 'Production': 'Production', 'On demand · Europe / Switzerland where available': 'À la commande · Europe / Suisse selon disponibilité', 'Inventory': 'Stock', 'None': 'Aucun', 'Launch price': 'Prix de lancement', 'Final after sample approval': 'Final après validation des échantillons',
      'Collect the': 'Collectionner', 'image.': 'l’image.', 'Unframed museum-grade giclée photograph. One shared edition of 100 across all three sizes, with an individually numbered certificate of authenticity.': 'Photographie giclée non encadrée de qualité musée. Une édition commune de 100 pour les trois formats, avec certificat d’authenticité numéroté individuellement.', '01 Image': '01 Image', '02 Paper': '02 Papier', '03 Scale': '03 Échelle', 'Paper': 'Papier', 'Edition': 'Édition', '100 total · all sizes combined': '100 au total · tous formats confondus', 'Format': 'Format', 'Print only · supplied unframed': 'Tirage seul · livré non encadré', 'Join the launch list ↗': 'Rejoindre la liste de lancement ↗',
      '02 — Curator’s selection': '02 — Sélection curatoriale', 'Find your': 'Trouver votre', 'scale.': 'format.', 'Curator’s selection': 'Sélection curatoriale', 'Small · CHF 150–200': 'Petit · CHF 150–200', 'Medium · CHF 300–450': 'Moyen · CHF 300–450', 'Large · CHF 600–800': 'Grand · CHF 600–800', 'Preview 01 · Small': 'Aperçu 01 · Petit', 'Preview 02 · Medium': 'Aperçu 02 · Moyen', 'Preview 03 · Large': 'Aperçu 03 · Grand', 'Unframed · Museum-grade paper': 'Non encadré · Papier qualité musée', 'Every photograph is part of an edition of 100 in total across all sizes.': 'Chaque photographie fait partie d’une édition totale de 100, tous formats confondus.', 'Request collector access ↗': 'Demander l’accès collectionneur ↗',
      '03 — Ben Taleb / Limited photography': '03 — Ben Taleb / Photographie limitée', 'Made to live': 'Faite pour vivre', 'with you.': 'avec vous.', 'Unframed black-and-white fine-art photographs, produced only after purchase on museum-grade Hahnemühle Photo Rag 308 gsm using archival pigment inks. Every image is limited to 100 numbered prints in total across all sizes.': 'Photographies d’art noir et blanc non encadrées, produites uniquement après achat sur papier Hahnemühle Photo Rag 308 g/m² de qualité musée avec des encres pigmentaires d’archive. Chaque image est limitée à 100 tirages numérotés au total, tous formats confondus.', 'Small': 'Petit', 'Medium': 'Moyen', 'Large': 'Grand', 'Print only; frame and mounting are not included. Each approved edition will be registered through My Art Registry and accompanied by a signed certificate with its matching numbered hologram. Final dimensions and prices follow physical proofing, packaging and Swiss VAT review.': 'Tirage seul ; cadre et montage non inclus. Chaque édition approuvée sera enregistrée dans My Art Registry et accompagnée d’un certificat signé avec hologramme numéroté correspondant. Formats et prix finaux après épreuves, emballage et examen de la TVA suisse.', 'Join the collectors list ↗': 'Rejoindre la liste des collectionneurs ↗',
      '04 — Domus Radio': '04 — Radio Domus', 'selects.': 'sélectionne.', 'Official channel · Weekly transmission · 45–60 min': 'Chaîne officielle · Transmission hebdomadaire · 45–60 min', 'A weekly hour of music, references and new discoveries. Listen here or': 'Une heure hebdomadaire de musique, de références et de découvertes. Écoutez ici ou', 'open the Juice+ SoundCloud channel ↗': 'ouvrir la chaîne SoundCloud Juice+ ↗',
      '05 — Field Notes': '05 — Notes de terrain', 'Go there.': 'Y aller.', 'Look closely.': 'Regarder de près.', 'People, gallery visits, street art, exhibitions and the ideas shaping new work.': 'Personnes, visites de galeries, art urbain, expositions et idées qui façonnent de nouvelles œuvres.', 'Inside the image': 'Dans l’image', 'Art encounters and visual details from the places shaping culture now.': 'Rencontres artistiques et détails visuels des lieux qui façonnent la culture actuelle.', 'Human presence': 'Présence humaine', 'Figures, gestures and reflections observed in motion.': 'Figures, gestes et reflets observés en mouvement.', 'The city speaks': 'La ville parle', 'Temporary works, anonymous gestures and objects encountered outside.': 'Œuvres temporaires, gestes anonymes et objets rencontrés dehors.', 'View on Instagram ↗': 'Voir sur Instagram ↗',
      '06 — Events': '06 — Événements', 'Meet in': 'Se rencontrer dans', 'real space.': 'l’espace réel.', 'Pop-ups, gallery visits, atelier conversations and listening sessions. The first Domus Cultura programme is currently in development.': 'Pop-ups, visites de galeries, conversations d’atelier et sessions d’écoute. Le premier programme Domus Cultura est en développement.',
      'Editions, events and sound — sent occasionally': 'Éditions, événements et son — envoyés occasionnellement', 'Enter the': 'Entrer dans la', 'Email address': 'Adresse e-mail', 'No noise. Early access to drops, pop-ups and new projects.': 'Sans bruit. Accès anticipé aux sorties, pop-ups et nouveaux projets.',
      'Open call — artist submissions': 'Appel ouvert — candidatures artistiques', 'Back to Domus ↗': 'Retour à Domus ↗', 'Artist submissions / Rolling programme': 'Candidatures artistiques / Programme continu', 'Bring your work': 'Faites entrer votre travail', 'into the': 'dans la',
      'Domus Cultura welcomes considered proposals from artists, photographers, writers, sound practitioners and independent cultural projects.': 'Domus Cultura accueille les propositions réfléchies d’artistes, photographes, auteur·rices, praticien·nes du son et projets culturels indépendants.', 'Selected practices may be featured through an interview, studio visit, journal story, event, collaboration or limited-edition proposal.': 'Les pratiques sélectionnées peuvent être présentées dans un entretien, une visite d’atelier, un article, un événement, une collaboration ou une proposition d’édition limitée.',
      'What we look for': 'Ce que nous recherchons', 'A clear practice.': 'Une pratique claire.', 'A real point of view.': 'Un vrai point de vue.', 'Contemporary relevance': 'Pertinence contemporaine', 'Work that speaks to life now—socially, materially or imaginatively.': 'Un travail qui parle de la vie actuelle — socialement, matériellement ou par l’imaginaire.', 'Visual strength': 'Force visuelle', 'A coherent body of work with images suitable for thoughtful editorial presentation.': 'Un ensemble cohérent avec des images adaptées à une présentation éditoriale exigeante.', 'Human context': 'Contexte humain', 'A process, place or lived experience worth opening to a wider public.': 'Un processus, un lieu ou une expérience vécue qui mérite d’être partagé.', 'Mutual fit': 'Affinité mutuelle', 'A meaningful connection to art, architecture, photography, sound or public culture.': 'Un lien significatif avec l’art, l’architecture, la photographie, le son ou la culture publique.',
      'Submit your practice': 'Soumettre votre pratique', 'Tell us what': 'Dites-nous ce que', 'we should see.': 'nous devrions voir.', 'Send links rather than large attachments. Submissions are reviewed quarterly. We will contact you when there is a genuine editorial or collaborative fit.': 'Envoyez des liens plutôt que de lourdes pièces jointes. Les candidatures sont examinées chaque trimestre. Nous vous contacterons lorsqu’une véritable affinité éditoriale ou collaborative existe.',
      'Artist or collective name': 'Nom de l’artiste ou du collectif', 'City and country': 'Ville et pays', 'Website or Instagram': 'Site web ou Instagram', 'Primary practice': 'Pratique principale', 'Choose one': 'Choisir', 'Visual art': 'Arts visuels', 'Photography': 'Photographie', 'Street art': 'Art urbain', 'Sound / music': 'Son / musique', 'Architecture / design': 'Architecture / design', 'Writing / publishing': 'Écriture / édition', 'Multidisciplinary': 'Pluridisciplinaire', 'Project or body of work': 'Projet ou corpus', 'Portfolio link': 'Lien du portfolio', 'About the work': 'À propos du travail', 'Why Domus Cultura?': 'Pourquoi Domus Cultura ?',
      'I confirm that I own or control the rights to the submitted work and allow Domus Cultura to review the linked material. No rights are transferred by this submission.': 'Je confirme détenir ou contrôler les droits sur le travail soumis et autorise Domus Cultura à examiner les contenus liés. Aucun droit n’est transféré par cette candidature.', 'Prepare email submission ↗': 'Préparer la candidature par e-mail ↗', 'Your email application will open for your review before anything is sent.': 'Votre candidature s’ouvrira dans votre messagerie pour vérification avant tout envoi.', 'Your email application is ready. Review it in your email app, then send.': 'Votre candidature est prête. Vérifiez-la dans votre messagerie, puis envoyez-la.', 'Artist submissions': 'Candidatures artistiques', 'Reviewed quarterly': 'Examinées chaque trimestre', 'Switzerland — Worldwide': 'Suisse — Monde entier'
    },
    de: {
      'Domus Cultura — Creative Culture Office': 'Domus Cultura — Kreatives Kulturhaus', 'Shop — Domus Cultura': 'Shop — Domus Cultura', 'Artist Submissions — Domus Cultura': 'Künstlerbewerbungen — Domus Cultura',
      'Sounds': 'Sounds', 'Art Shop': 'Kunstshop', 'Art Journal': 'Kunstjournal', 'Events': 'Veranstaltungen', 'Art': 'Kunst',
      'Independent platform for art, architecture, image and sound · Switzerland': 'Unabhängige Plattform für Kunst, Architektur, Bild und Klang · Schweiz', 'A cultural house in motion.': 'Ein Kulturhaus in Bewegung.', 'Photography by Ben Taleb': 'Fotografie von Ben Taleb', 'Sound by Juice+': 'Sound von Juice+',
      '01 / Current': '01 / Aktuell', 'Cover story · Photography': 'Titelgeschichte · Fotografie', 'A visual journal of architecture, public space and the people who move through it.': 'Ein visuelles Journal über Architektur, öffentlichen Raum und die Menschen, die sich darin bewegen.', 'Enter the project ↗': 'Projekt entdecken ↗', 'Domus Index': 'Domus Index', 'Now': 'Jetzt',
      'Ben Taleb editions': 'Ben-Taleb-Editionen', 'Collect / Photography': 'Sammeln / Fotografie', 'Juice+ weekly selections': 'Wöchentliche Juice+-Auswahl', 'Listen / Sound': 'Hören / Sound', 'Atelier and gallery visits': 'Atelier- und Galeriebesuche', 'Attend / Events': 'Teilnehmen / Events', 'Domus objects and editions': 'Domus-Objekte und Editionen', 'Discover / Shop': 'Entdecken / Shop',
      '02 / Field notes': '02 / Feldnotizen', 'People, art': 'Menschen, Kunst', 'and the': 'und die', 'street.': 'Straße.', 'Follow @domuscultura ↗': '@domuscultura folgen ↗', 'Human presence / Reflection': 'Menschliche Präsenz / Spiegelung', 'Exhibition detail / Art': 'Ausstellungsdetail / Kunst', 'Space / Form': 'Raum / Form', 'Street art / Found work': 'Street Art / Fundstück', 'People / Collective space': 'Menschen / Gemeinsamer Raum',
      '03 / Position': '03 / Position', 'Culture is a space': 'Kultur ist ein Raum', 'we build': 'den wir', 'together.': 'gemeinsam bauen.', 'Domus Cultura brings contemporary art into everyday life through editions, encounters, field notes and sound. It is a platform for looking closely, listening deeply and making new work possible.': 'Domus Cultura bringt zeitgenössische Kunst durch Editionen, Begegnungen, Feldnotizen und Klang in den Alltag. Eine Plattform für genaues Sehen, tiefes Hören und neue Arbeiten.',
      '04 / Art': '04 / Kunst', 'Architecture, public space and the quiet theatre of the city.': 'Architektur, öffentlicher Raum und das stille Theater der Stadt.', 'Fine-art photograph': 'Fine-Art-Fotografie', 'View the first editions ↗': 'Erste Editionen ansehen ↗', '05 / Image': '05 / Bild', 'Observe first.': 'Zuerst beobachten.', 'Then frame.': 'Dann rahmen.', 'The photographic practice moves between constructed space and human presence—between distance, rhythm and direct encounter.': 'Die fotografische Praxis bewegt sich zwischen gebautem Raum und menschlicher Präsenz — zwischen Distanz, Rhythmus und direkter Begegnung.', 'Original art inquiries ↗': 'Anfragen zu Originalwerken ↗',
      '06 / Events': '06 / Veranstaltungen', 'Gatherings with': 'Begegnungen mit', 'a point of view.': 'einer Haltung.', 'Coming soon': 'Demnächst', 'Art, conversation and a live selection by Juice+.': 'Kunst, Gespräch und eine Live-Auswahl von Juice+.', 'Register interest ↗': 'Interesse anmelden ↗', 'In development': 'In Entwicklung', 'Artist & Atelier Visits': 'Künstler- und Atelierbesuche', 'Small-format encounters with artists and their working spaces.': 'Begegnungen im kleinen Rahmen mit Kunstschaffenden und ihren Arbeitsorten.', 'Join the list ↗': 'Liste beitreten ↗',
      'Weekly selections by Juice+': 'Wöchentliche Auswahl von Juice+', 'Listen ↗': 'Hören ↗', 'Visits, conversations and field notes': 'Besuche, Gespräche und Feldnotizen', 'Read ↗': 'Lesen ↗', 'Limited editions and cultural objects': 'Limitierte Editionen und Kulturobjekte', 'Collect ↗': 'Sammeln ↗',
      'Open call / Artists': 'Open Call / Kunstschaffende', 'Should we know': 'Sollten wir Ihre', 'your work?': 'Arbeit kennen?', 'Domus Cultura accepts rolling submissions for editorial features, studio visits, events and future collaborations.': 'Domus Cultura nimmt laufend Bewerbungen für redaktionelle Porträts, Atelierbesuche, Veranstaltungen und zukünftige Kooperationen an.', 'Submit your practice ↗': 'Arbeit einreichen ↗', '07 / Contact': '07 / Kontakt', 'Ideas, commissions': 'Ideen, Aufträge', 'and collaborations.': 'und Kooperationen.', 'Switzerland · Worldwide': 'Schweiz · Weltweit',
      'Independent art, editions & sound from Switzerland — Made to order, never held in inventory': 'Unabhängige Kunst, Editionen und Sound aus der Schweiz — Auf Bestellung gefertigt, nie auf Lager', 'The Domus Cultura store': 'Der Domus-Cultura-Shop', 'Art lives': 'Kunst lebt', 'among us.': 'unter uns.', 'Limited photography by Ben Taleb, cultural objects, artist collaborations and weekly sound selections by Juice+.': 'Limitierte Fotografie von Ben Taleb, Kulturobjekte, Künstlerkooperationen und wöchentliche Soundauswahl von Juice+.',
      '01 — Shop the first drop': '01 — Ersten Drop entdecken', 'Collect the': 'Sammeln Sie die', 'world we see.': 'Welt, die wir sehen.', 'Three focused collections, produced responsibly and released in considered quantities.': 'Drei fokussierte Kollektionen, verantwortungsvoll produziert und in bewussten Mengen veröffentlicht.', 'Fine-art photography': 'Fine-Art-Fotografie', 'Ben Taleb Editions': 'Ben-Taleb-Editionen', 'From CHF 150': 'Ab CHF 150', 'Unframed black-and-white photographs on museum-grade Hahnemühle paper · three sizes · edition of 100.': 'Ungerahmte Schwarz-Weiß-Fotografien auf Hahnemühle-Papier in Museumsqualität · drei Größen · 100er-Edition.', 'See three views ↗': 'Drei Ansichten ↗',
      'Objects & apparel': 'Objekte & Kleidung', 'Domus Essentials': 'Domus Essentials', 'From CHF 25': 'Ab CHF 25', 'T-shirts, sweatshirts, caps, mugs, totes and postcard sets—made only after purchase, with no inventory.': 'T-Shirts, Sweatshirts, Caps, Tassen, Taschen und Postkartensets — erst nach dem Kauf gefertigt, ohne Lagerbestand.', 'Guest artists': 'Gastkünstler', 'Domus Collaborations': 'Domus Kooperationen', 'Limited': 'Limitiert', 'Small-run editions made with invited artists across image, sound and material.': 'Kleinauflagen mit eingeladenen Kunstschaffenden aus Bild, Klang und Material.', 'Propose a collaboration ↗': 'Kooperation vorschlagen ↗',
      'Product viewer — Object study': 'Produktansicht — Objektstudie', 'Click a view to inspect the front, reverse and material detail before ordering.': 'Klicken Sie auf eine Ansicht, um Vorderseite, Rückseite und Material vor der Bestellung zu prüfen.', 'Front / heavyweight organic cotton': 'Vorderseite / schwere Bio-Baumwolle', 'Reverse / numbered first drop': 'Rückseite / nummerierter erster Drop', 'Detail / collar and print texture': 'Detail / Kragen und Druckstruktur', 'Full image / Looking Up, Ben Taleb': 'Gesamtbild / Looking Up, Ben Taleb', 'Paper detail / natural-white cotton rag': 'Papierdetail / naturweißes Baumwollpapier', 'Scale view / medium edition': 'Größenansicht / mittlere Edition',
      'Wear the': 'Tragen Sie das', 'house.': 'Haus.', 'Produced only when ordered. The launch garment will be sampled for fabric weight, print durability and fit before checkout opens.': 'Nur auf Bestellung produziert. Stoffgewicht, Druckhaltbarkeit und Passform werden vor Verkaufsstart bemustert.', '01 Front': '01 Vorne', '02 Reverse': '02 Hinten', '03 Detail': '03 Detail', 'Production': 'Produktion', 'On demand · Europe / Switzerland where available': 'Auf Bestellung · Europa / Schweiz, wo verfügbar', 'Inventory': 'Lagerbestand', 'None': 'Keiner', 'Launch price': 'Startpreis', 'Final after sample approval': 'Final nach Musterfreigabe',
      'Collect the': 'Sammeln Sie das', 'image.': 'Bild.', 'Unframed museum-grade giclée photograph. One shared edition of 100 across all three sizes, with an individually numbered certificate of authenticity.': 'Ungerahmte Giclée-Fotografie in Museumsqualität. Eine gemeinsame 100er-Edition über alle drei Größen, mit individuell nummeriertem Echtheitszertifikat.', '01 Image': '01 Bild', '02 Paper': '02 Papier', '03 Scale': '03 Größe', 'Paper': 'Papier', 'Edition': 'Edition', '100 total · all sizes combined': '100 insgesamt · alle Größen zusammen', 'Format': 'Format', 'Print only · supplied unframed': 'Nur Print · ungerahmt geliefert', 'Join the launch list ↗': 'Startliste beitreten ↗',
      '02 — Curator’s selection': '02 — Kuratorische Auswahl', 'Find your': 'Finden Sie Ihre', 'scale.': 'Größe.', 'Small · CHF 150–200': 'Klein · CHF 150–200', 'Medium · CHF 300–450': 'Mittel · CHF 300–450', 'Large · CHF 600–800': 'Groß · CHF 600–800', 'Preview 01 · Small': 'Vorschau 01 · Klein', 'Preview 02 · Medium': 'Vorschau 02 · Mittel', 'Preview 03 · Large': 'Vorschau 03 · Groß', 'Unframed · Museum-grade paper': 'Ungerahmt · Papier in Museumsqualität', 'Every photograph is part of an edition of 100 in total across all sizes.': 'Jede Fotografie gehört zu einer Gesamtauflage von 100 über alle Größen.', 'Request collector access ↗': 'Sammlerzugang anfragen ↗', '03 — Ben Taleb / Limited photography': '03 — Ben Taleb / Limitierte Fotografie', 'Made to live': 'Gemacht für ein Leben', 'with you.': 'mit Ihnen.', 'Unframed black-and-white fine-art photographs, produced only after purchase on museum-grade Hahnemühle Photo Rag 308 gsm using archival pigment inks. Every image is limited to 100 numbered prints in total across all sizes.': 'Ungerahmte Schwarz-Weiß-Fine-Art-Fotografien, erst nach dem Kauf auf Hahnemühle Photo Rag 308 g/m² in Museumsqualität mit archivfesten Pigmenttinten produziert. Jedes Motiv ist über alle Größen hinweg auf insgesamt 100 nummerierte Abzüge limitiert.', 'Small': 'Klein', 'Medium': 'Mittel', 'Large': 'Groß', 'Join the collectors list ↗': 'Zur Sammlerliste ↗',
      '04 — Domus Radio': '04 — Domus Radio', 'selects.': 'wählt aus.', 'Official channel · Weekly transmission · 45–60 min': 'Offizieller Kanal · Wöchentliche Sendung · 45–60 Min.', 'A weekly hour of music, references and new discoveries. Listen here or': 'Eine wöchentliche Stunde Musik, Referenzen und Entdeckungen. Hier hören oder', 'open the Juice+ SoundCloud channel ↗': 'den Juice+ SoundCloud-Kanal öffnen ↗',
      '05 — Field Notes': '05 — Feldnotizen', 'Go there.': 'Hingehen.', 'Look closely.': 'Genau hinsehen.', 'People, gallery visits, street art, exhibitions and the ideas shaping new work.': 'Menschen, Galeriebesuche, Street Art, Ausstellungen und Ideen, die neue Arbeiten prägen.', 'Inside the image': 'Im Bild', 'Art encounters and visual details from the places shaping culture now.': 'Kunstbegegnungen und visuelle Details aus Orten, die Kultur heute prägen.', 'Human presence': 'Menschliche Präsenz', 'Figures, gestures and reflections observed in motion.': 'Figuren, Gesten und Spiegelungen in Bewegung.', 'The city speaks': 'Die Stadt spricht', 'Temporary works, anonymous gestures and objects encountered outside.': 'Temporäre Werke, anonyme Gesten und draußen gefundene Objekte.', 'View on Instagram ↗': 'Auf Instagram ansehen ↗',
      '06 — Events': '06 — Veranstaltungen', 'Meet in': 'Begegnung im', 'real space.': 'realen Raum.', 'Pop-ups, gallery visits, atelier conversations and listening sessions. The first Domus Cultura programme is currently in development.': 'Pop-ups, Galeriebesuche, Ateliergespräche und Hörsessions. Das erste Domus-Cultura-Programm ist in Entwicklung.', 'Editions, events and sound — sent occasionally': 'Editionen, Veranstaltungen und Sound — gelegentlich versendet', 'Enter the': 'Betreten Sie das', 'Email address': 'E-Mail-Adresse', 'No noise. Early access to drops, pop-ups and new projects.': 'Kein Lärm. Früher Zugang zu Drops, Pop-ups und neuen Projekten.',
      'Open call — artist submissions': 'Open Call — Künstlerbewerbungen', 'Back to Domus ↗': 'Zurück zu Domus ↗', 'Artist submissions / Rolling programme': 'Künstlerbewerbungen / Laufendes Programm', 'Bring your work': 'Bringen Sie Ihre Arbeit', 'into the': 'in das', 'Domus Cultura welcomes considered proposals from artists, photographers, writers, sound practitioners and independent cultural projects.': 'Domus Cultura begrüßt durchdachte Vorschläge von Kunstschaffenden, Fotograf:innen, Autor:innen, Klangpraktiker:innen und unabhängigen Kulturprojekten.', 'Selected practices may be featured through an interview, studio visit, journal story, event, collaboration or limited-edition proposal.': 'Ausgewählte Positionen können in einem Interview, Atelierbesuch, Journalbeitrag, Event, einer Kooperation oder limitierten Edition vorgestellt werden.',
      'What we look for': 'Was wir suchen', 'A clear practice.': 'Eine klare Praxis.', 'A real point of view.': 'Eine echte Haltung.', 'Contemporary relevance': 'Zeitgenössische Relevanz', 'Work that speaks to life now—socially, materially or imaginatively.': 'Arbeiten, die das heutige Leben sozial, materiell oder imaginativ ansprechen.', 'Visual strength': 'Visuelle Stärke', 'A coherent body of work with images suitable for thoughtful editorial presentation.': 'Ein kohärentes Werk mit Bildern für eine sorgfältige redaktionelle Präsentation.', 'Human context': 'Menschlicher Kontext', 'A process, place or lived experience worth opening to a wider public.': 'Ein Prozess, Ort oder eine gelebte Erfahrung, die einem größeren Publikum zugänglich sein sollte.', 'Mutual fit': 'Gemeinsame Passung', 'A meaningful connection to art, architecture, photography, sound or public culture.': 'Eine sinnvolle Verbindung zu Kunst, Architektur, Fotografie, Klang oder öffentlicher Kultur.',
      'Submit your practice': 'Arbeit einreichen', 'Tell us what': 'Zeigen Sie uns, was', 'we should see.': 'wir sehen sollten.', 'Send links rather than large attachments. Submissions are reviewed quarterly. We will contact you when there is a genuine editorial or collaborative fit.': 'Senden Sie Links statt großer Anhänge. Bewerbungen werden vierteljährlich geprüft. Wir melden uns bei echter redaktioneller oder kollaborativer Passung.', 'Artist or collective name': 'Name des Künstlers oder Kollektivs', 'City and country': 'Stadt und Land', 'Website or Instagram': 'Website oder Instagram', 'Primary practice': 'Hauptpraxis', 'Choose one': 'Bitte wählen', 'Visual art': 'Bildende Kunst', 'Photography': 'Fotografie', 'Street art': 'Street Art', 'Sound / music': 'Klang / Musik', 'Architecture / design': 'Architektur / Design', 'Writing / publishing': 'Schreiben / Publizieren', 'Multidisciplinary': 'Multidisziplinär', 'Project or body of work': 'Projekt oder Werkgruppe', 'Portfolio link': 'Portfolio-Link', 'About the work': 'Über die Arbeit', 'Why Domus Cultura?': 'Warum Domus Cultura?',
      'I confirm that I own or control the rights to the submitted work and allow Domus Cultura to review the linked material. No rights are transferred by this submission.': 'Ich bestätige, dass ich die Rechte an der eingereichten Arbeit besitze oder kontrolliere und Domus Cultura die Prüfung der verlinkten Inhalte erlaube. Durch diese Einreichung werden keine Rechte übertragen.', 'Prepare email submission ↗': 'E-Mail-Bewerbung vorbereiten ↗', 'Your email application will open for your review before anything is sent.': 'Ihre Bewerbung öffnet sich zur Prüfung im E-Mail-Programm, bevor etwas gesendet wird.', 'Your email application is ready. Review it in your email app, then send.': 'Ihre Bewerbung ist bereit. Prüfen Sie sie im E-Mail-Programm und senden Sie sie anschließend.', 'Artist submissions': 'Künstlerbewerbungen', 'Reviewed quarterly': 'Vierteljährlich geprüft', 'Switzerland — Worldwide': 'Schweiz — Weltweit'
    },
    es: {
      'Domus Cultura — Creative Culture Office': 'Domus Cultura — Casa cultural creativa', 'Shop — Domus Cultura': 'Tienda — Domus Cultura', 'Artist Submissions — Domus Cultura': 'Convocatoria de artistas — Domus Cultura',
      'Sounds': 'Sonidos', 'Art Shop': 'Tienda de arte', 'Art Journal': 'Diario de arte', 'Events': 'Eventos', 'Art': 'Arte',
      'Independent platform for art, architecture, image and sound · Switzerland': 'Plataforma independiente de arte, arquitectura, imagen y sonido · Suiza', 'A cultural house in motion.': 'Una casa cultural en movimiento.', 'Photography by Ben Taleb': 'Fotografía de Ben Taleb', 'Sound by Juice+': 'Sonido de Juice+',
      '01 / Current': '01 / Actualidad', 'Cover story · Photography': 'Portada · Fotografía', 'A visual journal of architecture, public space and the people who move through it.': 'Un diario visual de arquitectura, espacio público y las personas que lo recorren.', 'Enter the project ↗': 'Entrar al proyecto ↗', 'Domus Index': 'Índice Domus', 'Now': 'Ahora',
      'Ben Taleb editions': 'Ediciones Ben Taleb', 'Collect / Photography': 'Coleccionar / Fotografía', 'Juice+ weekly selections': 'Selecciones semanales de Juice+', 'Listen / Sound': 'Escuchar / Sonido', 'Atelier and gallery visits': 'Visitas a talleres y galerías', 'Attend / Events': 'Asistir / Eventos', 'Domus objects and editions': 'Objetos y ediciones Domus', 'Discover / Shop': 'Descubrir / Tienda',
      '02 / Field notes': '02 / Notas de campo', 'People, art': 'Personas, arte', 'and the': 'y la', 'street.': 'calle.', 'Follow @domuscultura ↗': 'Seguir @domuscultura ↗', 'Human presence / Reflection': 'Presencia humana / Reflejo', 'Exhibition detail / Art': 'Detalle de exposición / Arte', 'Space / Form': 'Espacio / Forma', 'Street art / Found work': 'Arte urbano / Obra encontrada', 'People / Collective space': 'Personas / Espacio colectivo',
      '03 / Position': '03 / Posición', 'Culture is a space': 'La cultura es un espacio', 'we build': 'que construimos', 'together.': 'juntos.', 'Domus Cultura brings contemporary art into everyday life through editions, encounters, field notes and sound. It is a platform for looking closely, listening deeply and making new work possible.': 'Domus Cultura lleva el arte contemporáneo a la vida cotidiana mediante ediciones, encuentros, notas de campo y sonido. Una plataforma para mirar de cerca, escuchar profundamente y hacer posible nuevas obras.',
      '04 / Art': '04 / Arte', 'Architecture, public space and the quiet theatre of the city.': 'Arquitectura, espacio público y el teatro silencioso de la ciudad.', 'Fine-art photograph': 'Fotografía artística', 'View the first editions ↗': 'Ver las primeras ediciones ↗', '05 / Image': '05 / Imagen', 'Observe first.': 'Observar primero.', 'Then frame.': 'Después encuadrar.', 'The photographic practice moves between constructed space and human presence—between distance, rhythm and direct encounter.': 'La práctica fotográfica se mueve entre el espacio construido y la presencia humana: entre distancia, ritmo y encuentro directo.', 'Original art inquiries ↗': 'Consultas sobre obra original ↗',
      '06 / Events': '06 / Eventos', 'Gatherings with': 'Encuentros con', 'a point of view.': 'un punto de vista.', 'Coming soon': 'Próximamente', 'Art, conversation and a live selection by Juice+.': 'Arte, conversación y selección en directo de Juice+.', 'Register interest ↗': 'Registrar interés ↗', 'In development': 'En desarrollo', 'Artist & Atelier Visits': 'Visitas a artistas y talleres', 'Small-format encounters with artists and their working spaces.': 'Encuentros en pequeño formato con artistas y sus espacios de trabajo.', 'Join the list ↗': 'Unirse a la lista ↗',
      'Weekly selections by Juice+': 'Selecciones semanales de Juice+', 'Listen ↗': 'Escuchar ↗', 'Visits, conversations and field notes': 'Visitas, conversaciones y notas de campo', 'Read ↗': 'Leer ↗', 'Limited editions and cultural objects': 'Ediciones limitadas y objetos culturales', 'Collect ↗': 'Coleccionar ↗',
      'Open call / Artists': 'Convocatoria / Artistas', 'Should we know': '¿Deberíamos conocer', 'your work?': 'tu trabajo?', 'Domus Cultura accepts rolling submissions for editorial features, studio visits, events and future collaborations.': 'Domus Cultura acepta propuestas de forma continua para reportajes, visitas de estudio, eventos y futuras colaboraciones.', 'Submit your practice ↗': 'Presentar tu práctica ↗', '07 / Contact': '07 / Contacto', 'Ideas, commissions': 'Ideas, encargos', 'and collaborations.': 'y colaboraciones.', 'Switzerland · Worldwide': 'Suiza · Todo el mundo',
      'Independent art, editions & sound from Switzerland — Made to order, never held in inventory': 'Arte independiente, ediciones y sonido desde Suiza — Producido bajo pedido, nunca en inventario', 'The Domus Cultura store': 'La tienda Domus Cultura', 'Art lives': 'El arte vive', 'among us.': 'entre nosotros.', 'Limited photography by Ben Taleb, cultural objects, artist collaborations and weekly sound selections by Juice+.': 'Fotografía limitada de Ben Taleb, objetos culturales, colaboraciones artísticas y selecciones sonoras semanales de Juice+.',
      '01 — Shop the first drop': '01 — Primera colección', 'Collect the': 'Colecciona el', 'world we see.': 'mundo que vemos.', 'Three focused collections, produced responsibly and released in considered quantities.': 'Tres colecciones precisas, producidas responsablemente y lanzadas en cantidades consideradas.', 'Fine-art photography': 'Fotografía artística', 'Ben Taleb Editions': 'Ediciones Ben Taleb', 'From CHF 150': 'Desde CHF 150', 'Unframed black-and-white photographs on museum-grade Hahnemühle paper · three sizes · edition of 100.': 'Fotografías en blanco y negro sin marco sobre papel Hahnemühle de calidad museo · tres tamaños · edición de 100.', 'See three views ↗': 'Ver tres vistas ↗',
      'Objects & apparel': 'Objetos y ropa', 'Domus Essentials': 'Esenciales Domus', 'From CHF 25': 'Desde CHF 25', 'T-shirts, sweatshirts, caps, mugs, totes and postcard sets—made only after purchase, with no inventory.': 'Camisetas, sudaderas, gorras, tazas, bolsas y postales, producidas solo después de la compra, sin inventario.', 'Guest artists': 'Artistas invitados', 'Domus Collaborations': 'Colaboraciones Domus', 'Limited': 'Limitado', 'Small-run editions made with invited artists across image, sound and material.': 'Ediciones pequeñas realizadas con artistas invitados en imagen, sonido y materia.', 'Propose a collaboration ↗': 'Proponer una colaboración ↗',
      'Product viewer — Object study': 'Visor de producto — Estudio del objeto', 'Click a view to inspect the front, reverse and material detail before ordering.': 'Haz clic en una vista para examinar el frente, el reverso y el material antes de pedir.', 'Front / heavyweight organic cotton': 'Frente / algodón orgánico grueso', 'Reverse / numbered first drop': 'Reverso / primera colección numerada', 'Detail / collar and print texture': 'Detalle / cuello y textura de impresión', 'Full image / Looking Up, Ben Taleb': 'Imagen completa / Looking Up, Ben Taleb', 'Paper detail / natural-white cotton rag': 'Detalle del papel / algodón blanco natural', 'Scale view / medium edition': 'Vista de escala / edición mediana',
      'Wear the': 'Viste la', 'house.': 'casa.', 'Produced only when ordered. The launch garment will be sampled for fabric weight, print durability and fit before checkout opens.': 'Producido solo bajo pedido. La prenda se probará para verificar gramaje, durabilidad de impresión y corte antes de abrir la venta.', '01 Front': '01 Frente', '02 Reverse': '02 Reverso', '03 Detail': '03 Detalle', 'Production': 'Producción', 'On demand · Europe / Switzerland where available': 'Bajo pedido · Europa / Suiza cuando esté disponible', 'Inventory': 'Inventario', 'None': 'Ninguno', 'Launch price': 'Precio de lanzamiento', 'Final after sample approval': 'Final tras aprobar las muestras',
      'Collect the': 'Colecciona la', 'image.': 'imagen.', 'Unframed museum-grade giclée photograph. One shared edition of 100 across all three sizes, with an individually numbered certificate of authenticity.': 'Fotografía giclée sin marco de calidad museo. Una edición compartida de 100 entre los tres tamaños, con certificado de autenticidad numerado individualmente.', '01 Image': '01 Imagen', '02 Paper': '02 Papel', '03 Scale': '03 Escala', 'Paper': 'Papel', 'Edition': 'Edición', '100 total · all sizes combined': '100 en total · todos los tamaños', 'Format': 'Formato', 'Print only · supplied unframed': 'Solo impresión · entregada sin marco', 'Join the launch list ↗': 'Unirse a la lista de lanzamiento ↗',
      '02 — Curator’s selection': '02 — Selección curatorial', 'Find your': 'Encuentra tu', 'scale.': 'escala.', 'Small · CHF 150–200': 'Pequeña · CHF 150–200', 'Medium · CHF 300–450': 'Mediana · CHF 300–450', 'Large · CHF 600–800': 'Grande · CHF 600–800', 'Preview 01 · Small': 'Vista 01 · Pequeña', 'Preview 02 · Medium': 'Vista 02 · Mediana', 'Preview 03 · Large': 'Vista 03 · Grande', 'Unframed · Museum-grade paper': 'Sin marco · Papel de calidad museo', 'Every photograph is part of an edition of 100 in total across all sizes.': 'Cada fotografía forma parte de una edición total de 100 entre todos los tamaños.', 'Request collector access ↗': 'Solicitar acceso de coleccionista ↗', '03 — Ben Taleb / Limited photography': '03 — Ben Taleb / Fotografía limitada', 'Made to live': 'Hecha para vivir', 'with you.': 'contigo.', 'Unframed black-and-white fine-art photographs, produced only after purchase on museum-grade Hahnemühle Photo Rag 308 gsm using archival pigment inks. Every image is limited to 100 numbered prints in total across all sizes.': 'Fotografías artísticas en blanco y negro sin marco, producidas solo después de la compra en papel Hahnemühle Photo Rag 308 g/m² de calidad museo con tintas pigmentadas de archivo. Cada imagen está limitada a 100 copias numeradas en total entre todos los tamaños.', 'Small': 'Pequeña', 'Medium': 'Mediana', 'Large': 'Grande', 'Join the collectors list ↗': 'Unirse a la lista de coleccionistas ↗',
      '04 — Domus Radio': '04 — Radio Domus', 'selects.': 'selecciona.', 'Official channel · Weekly transmission · 45–60 min': 'Canal oficial · Transmisión semanal · 45–60 min', 'A weekly hour of music, references and new discoveries. Listen here or': 'Una hora semanal de música, referencias y descubrimientos. Escucha aquí o', 'open the Juice+ SoundCloud channel ↗': 'abre el canal SoundCloud de Juice+ ↗',
      '05 — Field Notes': '05 — Notas de campo', 'Go there.': 'Ve allí.', 'Look closely.': 'Mira de cerca.', 'People, gallery visits, street art, exhibitions and the ideas shaping new work.': 'Personas, visitas a galerías, arte urbano, exposiciones e ideas que dan forma a nuevas obras.', 'Inside the image': 'Dentro de la imagen', 'Art encounters and visual details from the places shaping culture now.': 'Encuentros artísticos y detalles visuales de los lugares que dan forma a la cultura actual.', 'Human presence': 'Presencia humana', 'Figures, gestures and reflections observed in motion.': 'Figuras, gestos y reflejos observados en movimiento.', 'The city speaks': 'La ciudad habla', 'Temporary works, anonymous gestures and objects encountered outside.': 'Obras temporales, gestos anónimos y objetos encontrados afuera.', 'View on Instagram ↗': 'Ver en Instagram ↗',
      '06 — Events': '06 — Eventos', 'Meet in': 'Encontrarnos en el', 'real space.': 'espacio real.', 'Pop-ups, gallery visits, atelier conversations and listening sessions. The first Domus Cultura programme is currently in development.': 'Pop-ups, visitas a galerías, conversaciones de taller y sesiones de escucha. El primer programa Domus Cultura está en desarrollo.', 'Editions, events and sound — sent occasionally': 'Ediciones, eventos y sonido — envío ocasional', 'Enter the': 'Entra en la', 'Email address': 'Correo electrónico', 'No noise. Early access to drops, pop-ups and new projects.': 'Sin ruido. Acceso anticipado a lanzamientos, pop-ups y nuevos proyectos.',
      'Open call — artist submissions': 'Convocatoria abierta — propuestas de artistas', 'Back to Domus ↗': 'Volver a Domus ↗', 'Artist submissions / Rolling programme': 'Propuestas de artistas / Programa continuo', 'Bring your work': 'Trae tu trabajo', 'into the': 'a la', 'Domus Cultura welcomes considered proposals from artists, photographers, writers, sound practitioners and independent cultural projects.': 'Domus Cultura recibe propuestas cuidadas de artistas, fotógrafos, escritores, profesionales del sonido y proyectos culturales independientes.', 'Selected practices may be featured through an interview, studio visit, journal story, event, collaboration or limited-edition proposal.': 'Las prácticas seleccionadas podrán aparecer mediante entrevista, visita de estudio, artículo, evento, colaboración o propuesta de edición limitada.',
      'What we look for': 'Qué buscamos', 'A clear practice.': 'Una práctica clara.', 'A real point of view.': 'Un punto de vista real.', 'Contemporary relevance': 'Relevancia contemporánea', 'Work that speaks to life now—socially, materially or imaginatively.': 'Trabajo que habla de la vida actual de forma social, material o imaginativa.', 'Visual strength': 'Fuerza visual', 'A coherent body of work with images suitable for thoughtful editorial presentation.': 'Un cuerpo de trabajo coherente con imágenes adecuadas para una presentación editorial cuidada.', 'Human context': 'Contexto humano', 'A process, place or lived experience worth opening to a wider public.': 'Un proceso, lugar o experiencia vivida que merece abrirse a un público más amplio.', 'Mutual fit': 'Afinidad mutua', 'A meaningful connection to art, architecture, photography, sound or public culture.': 'Una conexión significativa con el arte, la arquitectura, la fotografía, el sonido o la cultura pública.',
      'Submit your practice': 'Presenta tu práctica', 'Tell us what': 'Cuéntanos qué', 'we should see.': 'deberíamos ver.', 'Send links rather than large attachments. Submissions are reviewed quarterly. We will contact you when there is a genuine editorial or collaborative fit.': 'Envía enlaces en lugar de archivos grandes. Las propuestas se revisan trimestralmente. Te contactaremos cuando exista una afinidad editorial o colaborativa real.', 'Artist or collective name': 'Nombre del artista o colectivo', 'City and country': 'Ciudad y país', 'Website or Instagram': 'Sitio web o Instagram', 'Primary practice': 'Práctica principal', 'Choose one': 'Elige una', 'Visual art': 'Artes visuales', 'Photography': 'Fotografía', 'Street art': 'Arte urbano', 'Sound / music': 'Sonido / música', 'Architecture / design': 'Arquitectura / diseño', 'Writing / publishing': 'Escritura / publicación', 'Multidisciplinary': 'Multidisciplinar', 'Project or body of work': 'Proyecto o cuerpo de obra', 'Portfolio link': 'Enlace al portfolio', 'About the work': 'Sobre el trabajo', 'Why Domus Cultura?': '¿Por qué Domus Cultura?',
      'I confirm that I own or control the rights to the submitted work and allow Domus Cultura to review the linked material. No rights are transferred by this submission.': 'Confirmo que poseo o controlo los derechos del trabajo presentado y permito que Domus Cultura revise el material enlazado. Esta propuesta no transfiere ningún derecho.', 'Prepare email submission ↗': 'Preparar propuesta por correo ↗', 'Your email application will open for your review before anything is sent.': 'La propuesta se abrirá en tu correo para que la revises antes de enviar.', 'Your email application is ready. Review it in your email app, then send.': 'Tu propuesta está lista. Revísala en tu correo y después envíala.', 'Artist submissions': 'Propuestas de artistas', 'Reviewed quarterly': 'Revisado trimestralmente', 'Switzerland — Worldwide': 'Suiza — Todo el mundo'
    }
  };

  // Keep shared headline fragments grammatical in both the collection and print contexts.
  Object.assign(translations.fr, { 'Collect the': 'Collectionnez' });
  Object.assign(translations.de, { 'Collect the': 'Sammeln Sie', 'world we see.': 'die Welt, die wir sehen.', 'image.': 'das Bild.' });
  Object.assign(translations.es, { 'Collect the': 'Colecciona', 'world we see.': 'el mundo que vemos.', 'image.': 'la imagen.' });
  Object.assign(translations.fr, {
    'Exhibition detail · Art': 'Détail d’exposition · Art', 'People · Public space': 'Personnes · Espace public', 'Street art · Found work': 'Art urbain · Œuvre trouvée',
    'Sound / Public sculpture': 'Son / Sculpture publique', 'City detail / Petals': 'Détail urbain / Pétales', 'Architecture / Structure': 'Architecture / Structure',
    'Public sculpture · Sound': 'Sculpture publique · Son', 'Instruments become architecture': 'Les instruments deviennent architecture', 'Sound and civic space meet in a monumental street-side form.': 'Le son et l’espace civique se rencontrent dans une forme monumentale installée dans la rue.',
    'Night culture · People': 'Culture nocturne · Personnes', 'After dark': 'À la nuit tombée', 'Human silhouettes, light and atmosphere from a shared nocturnal space.': 'Silhouettes humaines, lumière et atmosphère dans un espace nocturne partagé.',
    'City detail · Colour': 'Détail urbain · Couleur', 'Petals between stones': 'Des pétales entre les pierres', 'A small accidental composition where colour interrupts the street.': 'Une petite composition fortuite où la couleur interrompt la rue.',
    'Architecture · Urban systems': 'Architecture · Systèmes urbains', 'Systems and rhythm': 'Systèmes et rythme', 'Concrete, steel and repetition read as an abstract city drawing.': 'Le béton, l’acier et la répétition se lisent comme un dessin urbain abstrait.'
  });
  Object.assign(translations.de, {
    'Exhibition detail · Art': 'Ausstellungsdetail · Kunst', 'People · Public space': 'Menschen · Öffentlicher Raum', 'Street art · Found work': 'Street Art · Fundstück',
    'Sound / Public sculpture': 'Klang / Öffentliche Skulptur', 'City detail / Petals': 'Stadtdetail / Blütenblätter', 'Architecture / Structure': 'Architektur / Struktur',
    'Public sculpture · Sound': 'Öffentliche Skulptur · Klang', 'Instruments become architecture': 'Instrumente werden Architektur', 'Sound and civic space meet in a monumental street-side form.': 'Klang und öffentlicher Raum begegnen sich in einer monumentalen Form im Stadtraum.',
    'Night culture · People': 'Nachtkultur · Menschen', 'After dark': 'Nach Einbruch der Dunkelheit', 'Human silhouettes, light and atmosphere from a shared nocturnal space.': 'Menschliche Silhouetten, Licht und Atmosphäre in einem gemeinsam erlebten nächtlichen Raum.',
    'City detail · Colour': 'Stadtdetail · Farbe', 'Petals between stones': 'Blütenblätter zwischen Steinen', 'A small accidental composition where colour interrupts the street.': 'Eine kleine zufällige Komposition, in der Farbe die Straße unterbricht.',
    'Architecture · Urban systems': 'Architektur · Urbane Systeme', 'Systems and rhythm': 'Systeme und Rhythmus', 'Concrete, steel and repetition read as an abstract city drawing.': 'Beton, Stahl und Wiederholung lesen sich wie eine abstrakte Stadtzeichnung.'
  });
  Object.assign(translations.es, {
    'Exhibition detail · Art': 'Detalle de exposición · Arte', 'People · Public space': 'Personas · Espacio público', 'Street art · Found work': 'Arte urbano · Obra encontrada',
    'Sound / Public sculpture': 'Sonido / Escultura pública', 'City detail / Petals': 'Detalle urbano / Pétalos', 'Architecture / Structure': 'Arquitectura / Estructura',
    'Public sculpture · Sound': 'Escultura pública · Sonido', 'Instruments become architecture': 'Los instrumentos se vuelven arquitectura', 'Sound and civic space meet in a monumental street-side form.': 'El sonido y el espacio cívico se encuentran en una forma monumental instalada en la calle.',
    'Night culture · People': 'Cultura nocturna · Personas', 'After dark': 'Al caer la noche', 'Human silhouettes, light and atmosphere from a shared nocturnal space.': 'Siluetas humanas, luz y atmósfera en un espacio nocturno compartido.',
    'City detail · Colour': 'Detalle urbano · Color', 'Petals between stones': 'Pétalos entre las piedras', 'A small accidental composition where colour interrupts the street.': 'Una pequeña composición accidental donde el color interrumpe la calle.',
    'Architecture · Urban systems': 'Arquitectura · Sistemas urbanos', 'Systems and rhythm': 'Sistemas y ritmo', 'Concrete, steel and repetition read as an abstract city drawing.': 'El hormigón, el acero y la repetición se leen como un dibujo urbano abstracto.'
  });

  const ignoredParents = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT']);
  const textNodes = [];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let current;
  while ((current = walker.nextNode())) {
    const source = current.nodeValue.trim();
    if (!source || ignoredParents.has(current.parentElement?.tagName) || current.parentElement?.closest('[data-language-switcher]')) continue;
    textNodes.push({ node: current, source, original: current.nodeValue });
  }

  const attributes = [];
  document.querySelectorAll('[placeholder], [aria-label], img[alt]').forEach((element) => {
    ['placeholder', 'aria-label', 'alt'].forEach((name) => {
      if (element.hasAttribute(name)) attributes.push({ element, name, source: element.getAttribute(name) });
    });
  });

  const englishTitle = document.title;
  const translate = (source, language) => translations[language]?.[source] || source;
  window.domusTranslate = (source) => translate(source, document.documentElement.lang || 'en');

  function applyLanguage(language) {
    const selected = translations[language] ? language : 'en';
    document.documentElement.lang = selected;
    document.title = translate(englishTitle, selected);
    textNodes.forEach(({ node, source, original }) => {
      node.nodeValue = original.replace(source, translate(source, selected));
    });
    attributes.forEach(({ element, name, source }) => element.setAttribute(name, translate(source, selected)));
    document.querySelectorAll('[data-lang]').forEach((button) => {
      const active = button.dataset.lang === selected;
      button.classList.toggle('is-active', active);
      button.setAttribute('aria-pressed', String(active));
    });
    try { localStorage.setItem('domus-language', selected); } catch (_) {}
  }

  let initial = new URLSearchParams(window.location.search).get('lang');
  if (!translations[initial] && initial !== 'en') {
    try { initial = localStorage.getItem('domus-language'); } catch (_) { initial = 'en'; }
  }
  applyLanguage(initial || 'en');

  document.querySelectorAll('[data-lang]').forEach((button) => {
    button.addEventListener('click', () => applyLanguage(button.dataset.lang));
  });
})();
